
import Link from 'next/link'
import './globals.css'

export const metadata = {
  title: 'D E V - MATEUS MELO',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" >
      <body>
        <h1>Sistema: Olá mundo!</h1>
        <nav>
          <ul>
            <li>
              <Link href="/">Home</Link>
            </li>
            <li>
              <Link href="/users">Usuários</Link>
            </li>
            <li>
              <Link href="/login">Login</Link>
            </li>
          </ul>
        </nav>
        
        <div>{children}</div>
      </body>
    </html>
  )
}
