
import Link from 'next/link'
import './globals.css'

export const metadata = {
  title: 'D E V - MATEUS MELO',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" >
      <body>
        <div>{children}</div>
      </body>
    </html>
  )
}
